export const equipmentsData = [
  {
    id: 1,
    src: '/images/equipments/crane-1.jpeg',
    title: 'Crane',
    alt: 'Crane',
    subTitle: 'ipsum dolor sit amet',
    genre: 'cranes',
  },
  {
    id: 2,
    src: '/images/equipments/crane-2.jpeg',
    title: 'Crane',
    alt: 'Crane',
    subTitle: 'ipsum dolor sit amet',
    genre: 'cranes',
  },
  {
    id: 3,
    src: '/images/equipments/crane-3.jpeg',
    title: 'Crane',
    alt: 'Crane',
    subTitle: 'ipsum dolor sit amet',
    genre: 'cranes',
  },
  {
    id: 4,
    src: '/images/equipments/crane-4.jpeg',
    title: 'Crane',
    alt: 'Crane',
    subTitle: 'ipsum dolor sit amet',
    genre: 'cranes',
  },
  {
    id: 41,
    src: '/images/equipments/crane-5.jpeg',
    title: 'Crane',
    alt: 'Crane',
    subTitle: 'ipsum dolor sit amet',
    genre: 'cranes',
  },
  {
    id: 5,
    src: '/images/equipments/forklift-1.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    subTitle: 'ipsum dolor sit amet',
    genre: 'forklifts',
  },
  {
    id: 6,
    src: '/images/equipments/forklift-2.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    subTitle: 'ipsum dolor sit amet',
    genre: 'forklifts',
  },
  {
    id: 7,
    src: '/images/equipments/jcb-backhoe.jpeg',
    title: 'JCB Backhoe',
    alt: 'jcb-backhoe',
    subTitle: 'ipsum dolor sit amet',
    genre: 'jsb-backhoes',
  },
  {
    id: 8,
    src: '/images/equipments/manlift-1.jpeg',
    title: 'Manlift',
    alt: 'manlift',
    subTitle: 'ipsum dolor sit amet',
    genre: 'manlifts',
  },
  {
    id: 9,
    src: '/images/equipments/manlift-2.jpeg',
    title: 'Manlift',
    alt: 'manlifts',
    subTitle: 'ipsum dolor sit amet',
    genre: 'manlifts',
  },
  {
    id: 10,
    src: '/images/equipments/telehanlder-1.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 11,
    src: '/images/equipments/telehanlder-2.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 12,
    src: '/images/equipments/telehanlder-3.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 13,
    src: '/images/equipments/telehanlder-4.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 14,
    src: '/images/equipments/telehanlder-5.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 15,
    src: '/images/equipments/telehanlder-6.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 16,
    src: '/images/equipments/telehanlder-7.jpeg',
    title: 'Telehanlder and Forklift',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'telehanlders',
  },
  {
    id: 17,
    src: '/images/equipments/towerlight-1.jpeg',
    title: 'Tower Light',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'towerLights',
  },
  {
    id: 18,
    src: '/images/equipments/towerlight-2.jpeg',
    title: 'Tower Light',
    alt: 'telehanlder',
    subTitle: 'ipsum dolor sit amet',
    genre: 'towerLights',
  },
]
